language: python

python:
  - 2.7.11

env:
  - DEPS=true

before_install:
  - sudo apt-get update

install:
  - python setup.py clean build install

script:
  - python tests/test_multiple_connections.py
